<a href="https://colab.research.google.com/github/rafajaramillo/proyectos_colab/blob/google_colab/StarWars.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import pandas as pd
import requests

In [12]:
# function to get star wars characters
def GetStarWarsCharacters():
    response = requests.get('https://swapi.dev/api/people/')
    #response = requests.get('https://swapi.py4e.com/api/people/')
    data_dict = response.json()
    characters = data_dict['results']
    return characters

In [13]:
# let's try out our function. notice it's a list of dictionary.
GetStarWarsCharacters()

[{'name': 'Luke Skywalker',
  'height': '172',
  'mass': '77',
  'hair_color': 'blond',
  'skin_color': 'fair',
  'eye_color': 'blue',
  'birth_year': '19BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.dev/api/planets/1/',
  'films': ['https://swapi.dev/api/films/1/',
   'https://swapi.dev/api/films/2/',
   'https://swapi.dev/api/films/3/',
   'https://swapi.dev/api/films/6/'],
  'species': [],
  'vehicles': ['https://swapi.dev/api/vehicles/14/',
   'https://swapi.dev/api/vehicles/30/'],
  'starships': ['https://swapi.dev/api/starships/12/',
   'https://swapi.dev/api/starships/22/'],
  'created': '2014-12-09T13:50:51.644000Z',
  'edited': '2014-12-20T21:17:56.891000Z',
  'url': 'https://swapi.dev/api/people/1/'},
 {'name': 'C-3PO',
  'height': '167',
  'mass': '75',
  'hair_color': 'n/a',
  'skin_color': 'gold',
  'eye_color': 'yellow',
  'birth_year': '112BBY',
  'gender': 'n/a',
  'homeworld': 'https://swapi.dev/api/planets/1/',
  'films': ['https://swapi.dev/api/films/1/',
   'https://swapi.dev/api/films/2/',
   'https://swapi.dev/api/films/3/',
   'https://swapi.dev/api/films/4/',
   'https://swapi.dev/api/films/5/',
   'https://swapi.dev/api/films/6/'],
  'species': ['https://swapi.dev/api/species/2/'],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-10T15:10:51.357000Z',
  'edited': '2014-12-20T21:17:50.309000Z',
  'url': 'https://swapi.dev/api/people/2/'},
 {'name': 'R2-D2',
  'height': '96',
  'mass': '32',
  'hair_color': 'n/a',
  'skin_color': 'white, blue',
  'eye_color': 'red',
  'birth_year': '33BBY',
  'gender': 'n/a',
  'homeworld': 'https://swapi.dev/api/planets/8/',
  'films': ['https://swapi.dev/api/films/1/',
   'https://swapi.dev/api/films/2/',
   'https://swapi.dev/api/films/3/',
   'https://swapi.dev/api/films/4/',
   'https://swapi.dev/api/films/5/',
   'https://swapi.dev/api/films/6/'],
  'species': ['https://swapi.dev/api/species/2/'],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-10T15:11:50.376000Z',
  'edited': '2014-12-20T21:17:50.311000Z',
  'url': 'https://swapi.dev/api/people/3/'},
 {'name': 'Darth Vader',
  'height': '202',
  'mass': '136',
  'hair_color': 'none',
  'skin_color': 'white',
  'eye_color': 'yellow',
  'birth_year': '41.9BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.dev/api/planets/1/',
  'films': ['https://swapi.dev/api/films/1/',
   'https://swapi.dev/api/films/2/',
   'https://swapi.dev/api/films/3/',
   'https://swapi.dev/api/films/6/'],
  'species': [],
  'vehicles': [],
  'starships': ['https://swapi.dev/api/starships/13/'],
  'created': '2014-12-10T15:18:20.704000Z',
  'edited': '2014-12-20T21:17:50.313000Z',
  'url': 'https://swapi.dev/api/people/4/'},
 {'name': 'Leia Organa',
  'height': '150',
  'mass': '49',
  'hair_color': 'brown',
  'skin_color': 'light',
  'eye_color': 'brown',
  'birth_year': '19BBY',
  'gender': 'female',
  'homeworld': 'https://swapi.dev/api/planets/2/',
  'films': ['https://swapi.dev/api/films/1/',
   'https://swapi.dev/api/films/2/',
   'https://swapi.dev/api/films/3/',
   'https://swapi.dev/api/films/6/'],
  'species': [],
  'vehicles': ['https://swapi.dev/api/vehicles/30/'],
  'starships': [],
  'created': '2014-12-10T15:20:09.791000Z',
  'edited': '2014-12-20T21:17:50.315000Z',
  'url': 'https://swapi.dev/api/people/5/'},
 {'name': 'Owen Lars',
  'height': '178',
  'mass': '120',
  'hair_color': 'brown, grey',
  'skin_color': 'light',
  'eye_color': 'blue',
  'birth_year': '52BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.dev/api/planets/1/',
  'films': ['https://swapi.dev/api/films/1/',
   'https://swapi.dev/api/films/5/',
   'https://swapi.dev/api/films/6/'],
  'species': [],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-10T15:52:14.024000Z',
  'edited': '2014-12-20T21:17:50.317000Z',
  'url': 'https://swapi.dev/api/people/6/'},
 {'name': 'Beru Whitesun lars',
  'height': '165',
  'mass': '75',
  'hair_color': 'brown',
  'skin_color': 'light',
  'eye_color': 'blue',
  'birth_year': '47BBY',
  'gender': 'female',
  'homeworld': 'https://swapi.dev/api/planets/1/',
  'films': ['https://swapi.dev/api/films/1/',
   'https://swapi.dev/api/films/5/',
   'https://swapi.dev/api/films/6/'],
  'species': [],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-10T15:53:41.121000Z',
  'edited': '2014-12-20T21:17:50.319000Z',
  'url': 'https://swapi.dev/api/people/7/'},
 {'name': 'R5-D4',
  'height': '97',
  'mass': '32',
  'hair_color': 'n/a',
  'skin_color': 'white, red',
  'eye_color': 'red',
  'birth_year': 'unknown',
  'gender': 'n/a',
  'homeworld': 'https://swapi.dev/api/planets/1/',
  'films': ['https://swapi.dev/api/films/1/'],
  'species': ['https://swapi.dev/api/species/2/'],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-10T15:57:50.959000Z',
  'edited': '2014-12-20T21:17:50.321000Z',
  'url': 'https://swapi.dev/api/people/8/'},
 {'name': 'Biggs Darklighter',
  'height': '183',
  'mass': '84',
  'hair_color': 'black',
  'skin_color': 'light',
  'eye_color': 'brown',
  'birth_year': '24BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.dev/api/planets/1/',
  'films': ['https://swapi.dev/api/films/1/'],
  'species': [],
  'vehicles': [],
  'starships': ['https://swapi.dev/api/starships/12/'],
  'created': '2014-12-10T15:59:50.509000Z',
  'edited': '2014-12-20T21:17:50.323000Z',
  'url': 'https://swapi.dev/api/people/9/'},
 {'name': 'Obi-Wan Kenobi',
  'height': '182',
  'mass': '77',
  'hair_color': 'auburn, white',
  'skin_color': 'fair',
  'eye_color': 'blue-gray',
  'birth_year': '57BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.dev/api/planets/20/',
  'films': ['https://swapi.dev/api/films/1/',
   'https://swapi.dev/api/films/2/',
   'https://swapi.dev/api/films/3/',
   'https://swapi.dev/api/films/4/',
   'https://swapi.dev/api/films/5/',
   'https://swapi.dev/api/films/6/'],
  'species': [],
  'vehicles': ['https://swapi.dev/api/vehicles/38/'],
  'starships': ['https://swapi.dev/api/starships/48/',
   'https://swapi.dev/api/starships/59/',
   'https://swapi.dev/api/starships/64/',
   'https://swapi.dev/api/starships/65/',
   'https://swapi.dev/api/starships/74/'],
  'created': '2014-12-10T16:16:29.192000Z',
  'edited': '2014-12-20T21:17:50.325000Z',
  'url': 'https://swapi.dev/api/people/10/'}]

In [28]:
# example of reading the star-wars api
characters = GetStarWarsCharacters() # This function gets the people as json
character_df = pd.DataFrame(characters)
character_df

TypeError: ignored

In [29]:
import json

In [30]:
def GetStarWarsCharacters(pagina):
    parametros = {'page': pagina}  
    response = requests.get('https://swapi.dev/api/people/', params=parametros)
    #response = requests.get('https://swapi.py4e.com/api/people', params=parametros)
    data_dict = response.json()
    characters = data_dict['results']
    return characters

In [23]:
for n in range(9):
  characters = GetStarWarsCharacters(n+1) # This function gets the people as json
  character_df1 = pd.DataFrame(characters)  # convertimos el json en un DataFrame
  if n == 1:
    df_concat_Starwars = character_df1
  if n > 1:
    df_concat_Starwars = pd.concat([df_concat_Starwars, character_df1]) # aquí se concatena cada DataFrame

In [24]:
df_concat_Starwars

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,created,edited,url
0,Anakin Skywalker,188,84,blond,fair,blue,41.9BBY,male,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/4/, https://swapi...",[],"[https://swapi.dev/api/vehicles/44/, https://s...","[https://swapi.dev/api/starships/39/, https://...",2014-12-10T16:20:44.310000Z,2014-12-20T21:17:50.327000Z,https://swapi.dev/api/people/11/
1,Wilhuff Tarkin,180,unknown,"auburn, grey",fair,blue,64BBY,male,https://swapi.dev/api/planets/21/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],[],2014-12-10T16:26:56.138000Z,2014-12-20T21:17:50.330000Z,https://swapi.dev/api/people/12/
2,Chewbacca,228,112,brown,unknown,blue,200BBY,male,https://swapi.dev/api/planets/14/,"[https://swapi.dev/api/films/1/, https://swapi...",[https://swapi.dev/api/species/3/],[https://swapi.dev/api/vehicles/19/],"[https://swapi.dev/api/starships/10/, https://...",2014-12-10T16:42:45.066000Z,2014-12-20T21:17:50.332000Z,https://swapi.dev/api/people/13/
3,Han Solo,180,80,brown,fair,brown,29BBY,male,https://swapi.dev/api/planets/22/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],"[https://swapi.dev/api/starships/10/, https://...",2014-12-10T16:49:14.582000Z,2014-12-20T21:17:50.334000Z,https://swapi.dev/api/people/14/
4,Greedo,173,74,n/a,green,black,44BBY,male,https://swapi.dev/api/planets/23/,[https://swapi.dev/api/films/1/],[https://swapi.dev/api/species/4/],[],[],2014-12-10T17:03:30.334000Z,2014-12-20T21:17:50.336000Z,https://swapi.dev/api/people/15/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,Grievous,216,159,none,"brown, white","green, yellow",unknown,male,https://swapi.dev/api/planets/59/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/36/],[https://swapi.dev/api/vehicles/60/],[https://swapi.dev/api/starships/74/],2014-12-20T19:43:53.348000Z,2014-12-20T21:17:50.488000Z,https://swapi.dev/api/people/79/
8,Tarfful,234,136,brown,brown,blue,unknown,male,https://swapi.dev/api/planets/14/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/3/],[],[],2014-12-20T19:46:34.209000Z,2014-12-20T21:17:50.491000Z,https://swapi.dev/api/people/80/
9,Raymus Antilles,188,79,brown,light,brown,unknown,male,https://swapi.dev/api/planets/2/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],[],2014-12-20T19:49:35.583000Z,2014-12-20T21:17:50.493000Z,https://swapi.dev/api/people/81/
0,Sly Moore,178,48,none,pale,white,unknown,female,https://swapi.dev/api/planets/60/,"[https://swapi.dev/api/films/5/, https://swapi...",[],[],[],2014-12-20T20:18:37.619000Z,2014-12-20T21:17:50.496000Z,https://swapi.dev/api/people/82/
1,Tion Medon,206,80,none,grey,black,unknown,male,https://swapi.dev/api/planets/12/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/37/],[],[],2014-12-20T20:35:04.260000Z,2014-12-20T21:17:50.498000Z,https://swapi.dev/api/people/83/

In [35]:
# Vamos a filtrar sólo las columnas necesarias del DataFrame
filterSW_df = df_concat_Starwars[['name','height','mass','hair_color','skin_color', 'eye_color','birth_year','gender']]
filterSW_df

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender
0,Anakin Skywalker,188,84,blond,fair,blue,41.9BBY,male
1,Wilhuff Tarkin,180,unknown,"auburn, grey",fair,blue,64BBY,male
2,Chewbacca,228,112,brown,unknown,blue,200BBY,male
3,Han Solo,180,80,brown,fair,brown,29BBY,male
4,Greedo,173,74,n/a,green,black,44BBY,male
...,...,...,...,...,...,...,...,...
7,Grievous,216,159,none,"brown, white","green, yellow",unknown,male
8,Tarfful,234,136,brown,brown,blue,unknown,male
9,Raymus Antilles,188,79,brown,light,brown,unknown,male
0,Sly Moore,178,48,none,pale,white,unknown,female
1,Tion Medon,206,80,none,grey,black,unknown,male

In [34]:
# Grabando el archivo xlsx
filterSW_df.to_excel('StarWars_final_df.xlsx', index=False)